### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/fomo#12]
## What/Why?

As a developer, I want to structure the database, so that data is stored efficiently and easily queried by the application.

## Tasks

- [x] Plan data storage/tables
- [x] Create database and connect to frontend
- [x] Set up database with security rules (lock database)
- [x] Populate database with test data
