### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/fomo#2]
## What/Why?

As a user, I want to search for an event, so that I can find out additional information about that event.

## Tasks

- [x] Create genre card
- [x] Format search page
- [x] Sync Algolia with Firestore and configure
- [x] Auto-completion
- [x] Auto-correction
- [x] Filtering
