### ISSUE TITLE
Discover

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/fomo#3]
## What/Why?

As a user, I want to view categorized events, so that I can discover new events that I might be interested in.

## Tasks

- [x] Create event card
- [x] Create custom category with list view widget
- [x] Layout discover page
- [x] Implement featured carousel scrolling
