### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/fomo#4]
## What/Why?

As a user, I want to register and login in to the application, so that I am able to securely access its features.

## Tasks

- [x] Format login page
- [x] Format registration page
- [x] Forgot password
- [x] Remember me
- [ ] Stretch: Login with 3rd party
