### ISSUE TITLE
My Events

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/fomo#5]
## What/Why?

As a user, I want to save events and view them, so that I can focus on and manage the events I am most interested in.

## Tasks

- [x] Save an event
- [x] Create Date Card
- [x] Format My Events page, splitting into "interested" and "going"

**Comment by echadwick6** [comment]
Big Question, How are people gonna choose between interested and going easily? Bookmark doesn't really make it swift and easy
