### ISSUE TITLE
Data passage to event clicked and view all pages

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/fomo#65]
## What/Why?

As a user I want to view event data so that I can determine if I am interested in the event.

## Tasks

- [x] Pass data to these pages when routing
- [x] Refactor event clicked page to use real data
- [x] Refactor view all page to use real data

**Comment by echadwick6** [comment]
Waiting on Issue #61 to be completed
