### ISSUE TITLE
Search for events

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/fomo#76]
## What/Why?

As a user I want to search for events so that I can get more information about them.

## Tasks

- [x] Connect app with algolia index
- [x] Create search UI
- [x] Stream results from algolia
- [x] Filter by genre
