### ISSUE TITLE
Friends Local and Cloud Services Basic Functions

### ISSUE THREAD

**Issue by Pgibert3** [mjbernet3/fomo#77]
## Tasks

- [ ] Create a Friends Backend Service
- [ ] local Friend Functions for requesting, accepting, and refusing friend request
- [ ] cloud Friend Functions for updating friend status
